In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import tensorflow as tf

In [ ]:
print("tensorflow version: {}".format(tf.__version__))
print("eager Execution :{}".format(tf.executing_eagerly()))
print("keras version :{}".format(tf.keras.__version__))

tensorflow version: 2.20.0
eager Execution :True
keras version :3.12.0


In [ ]:
if tf.test.is_gpu_available():
    print("Running on GPU")
else:
    print("running on CPU")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
running on CPU


In [ ]:
ineuron=tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
ineuron.numpy()

np.int32(42)

In [ ]:
ineuron1=tf.constant(1,dtype=tf.int64)
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
ineuron_x=tf.constant([[4,2],[9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [ ]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [ ]:
print("shape",ineuron_x.shape)
print(ineuron_x.dtype)

shape (2, 2)
<dtype: 'int32'>


In [1]:
import tensorflow as tf

In [4]:
variable=tf.Variable([[1,2,3,4],[11,29,12,13]])
checkpoint=tf.train.Checkpoint(var=variable)
save_path=checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [11, 29, 12, 13]], dtype=int32)>


In [6]:
def f1(x,y):
    return tf.reduce_mean(input_tensor=tf.multiply(x**2,5)+y**2)

f2=tf.function(f1)
x=tf.constant([4.,-5.])
y=tf.constant([2.,3.])

assert f1(x,y).numpy()==f2(x,y).numpy()

Calculate gradient in Tensorflow

by using GradientTape() as tape and tape.watch(a)


In [7]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da=tape.gradient(c,a)
    print(dc_da)



tf.Tensor(
[[-0.6685041   0.52978075]
 [ 0.6608312  -0.23401457]], shape=(2, 2), dtype=float32)


In [8]:
a=tf.Variable(a)
with tf.GradientTape() as tape:
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da=tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.6685041   0.52978075]
 [ 0.6608312  -0.23401457]], shape=(2, 2), dtype=float32)


In [9]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        c=tf.sqrt(tf.square(a)+tf.square(b))
        dc_da=inner_tape.gradient(c,a)
    d2c_da2=outer_tape.gradient(dc_da,a)
    print(d2c_da2)

tf.Tensor(
[[0.62749857 1.0227001 ]
 [0.43828866 0.6003866 ]], shape=(2, 2), dtype=float32)
